# config/routes/nelmio_api_doc.yaml
app.swagger_ui:
    path: /api/doc
    controller: nelmio_api_doc.controller.swagger

app.swagger_json:
    path: /api/doc.json
    controller: nelmio_api_doc.controller.swagger_json
